// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://belfsewcxeecvpxdxhxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbGZzZXdjeGVlY3ZweGR4aHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzYxMTUsImV4cCI6MjA1OTQ1MjExNX0.4_gMXHMMQE5xGG3ffJU9C53RjgseYHEk20H1L-Bc81Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);